version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
    - pip install pdm
    - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm install --dev
    pre_build:
    - pdm run jupyter-book config sphinx docs/

python:
  install:
  - method: pip
    path: .

sphinx:
  builder: html
