name: build
on: [push, pull_request]
env:
  PY_COLORS: "1"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.x']
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pdm sync --dev
      - name: Run tests
        run: pdm run -v pytest autobean_refactor -k 'not benchmark' --cov autobean_refactor --cov-report xml
      - name: Run type checks
        run: pdm run -v mypy autobean_refactor
      - name: Upload coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Run benchmark
        run: pdm run -v pytest autobean_refactor -sv -k 'benchmark'
